$('.owl-carousel').owlCarousel({
    loop:true,
    margin:7,
    nav:false,
    responsive:{
        0:{
            items:3
        },
        750:{
            items:6
        },
        1300:{
            items:8
        }
    }
})